project_id = "viori"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173", "https://YOUR_DOMAIN.nl"]
enable_signup = true

[storage]
enabled = true
file_size_limit = "10MiB"
